### ISSUE TITLE
Optimize certain mods for QuakeSpasmVR.

### ISSUE THREAD

**Issue by ni1chigo2115** [codeflorist/quakespasm-openvr#3]
https://quakeone.com/forum/quake-mod-releases/finished-works/283295-osjc-s-enhanced-quake1-model-conversions-pack-v1
Not very good news, but I found a mod that forces the HD model of the Q1 remaster to be applied to QuakeSpasm.
Should I use cvar to fix it?

**Comment by codeflorist** [comment]
@ni1chigo2115 I haven't seen this before, but it looks very interesting. What is exactly the problem with it? I assume the weapon offsets/positions?

**Comment by ni1chigo2115** [comment]
Yes, the main problem is that it replaces existing vanilla assets, so it is not registered in the configuration file, and the offset of the weapon will be vertically and horizontally off-set. (The best thing would be to be able to adjust the weapons one by one ingame, but that would be difficult.)

I know the most solid thing to do would be to make a dedicated model for quakespasm-openvr, but I don't think it has received much attention yet.
(I'd really like to set the angle for each weapon as well, but if I have to be that particular about it, I'd rather make a dedicated model for VR.)

**Comment by codeflorist** [comment]
@ni1chigo2115

Check out this release candidate for the next version:
https://github.com/gameflorist/quakespasm-openvr/releases/download/untagged-dca695b0a072b9f91e09/quakespasm-openvr-0.96.0bRC1_win64.zip

With it you can now use the enhanced models with already correctly applied offsets and scalings out-of-the-box. 

There are 2 ways to use them with Quakespasm-OpenVR:

- Extract the `enhanced` folder of the OSJC's mod into your `Quake` folder, and start the game with `-game enhanced`. I can check for the mod this way and automatically load specific offsets. (It is already done this way also for Arcane Dimensions)
- If you want to use the new models globally with all expansions and add-ons, rename `pak0.pak` from the `enhanced` folder by changing the `0` to a number higher then the highest existing `pak`-file inside your `id1` folder. If you are using `pak` files from vanilla Quake this will be `pak2.pak`, and if your are using the Re-Release, it will be `pak1.pak`. I have no real way to check for this thou, so i added a new VR option in-game called `Gun Model Offsets` (cvar `vr_gunmodeloffsets`). Switching this from `Vanilla` to `Enhanced` will apply the correct offsets.

I have also included this info in the [Readme](https://github.com/gameflorist/quakespasm-openvr#enhanced-models-from-quake-re-release).

Feel free to test the Release Candidate and let my know of any better suited cvars than the ones i came up with!

I also tried implementing weapon-specific angle-cvars, but it's a bit problematic, since it will also change the aiming/projectile/crosshair angle - resulting in different shooting angles per weapon, which i find confusing when switching weapons. I'm afraid decoupling shooting from weapon angles would be a more complex code change. Though i'd gladly accept  a pull request for it!

Some enhanced weapons (didn't check vanillas) do indeed have minor differences in angles from the rest, namely: Shotgun, Super Shotgun and Rocket Launcher. But i think this is barely noticable while playing. You could of course still change the angles in the models themselves.

PS: Many thanks again for bringing this mod to my attention! It's a great enhancement for QuakeSpasm-OpenVR. 😊👍

**Comment by codeflorist** [comment]
@ni1chigo2115

I've now also added support for the Authentic Model Improvements Pack available here:
https://github.com/NightFright2k19/quake_authmdl

The change is included in -0.96.0bRC2 available here: https://github.com/gameflorist/quakespasm-openvr/releases/download/untagged-3f61904d5dbea6a87991/quakespasm-openvr-0.96.0bRC2_win64.zip

`Gun Model Offsets` has to be set to `Authentic` for the correct offsets to be applied.

**Comment by ni1chigo2115** [comment]
If I see something that looks good and needs to be modified, I would like to be contacted.
(I'd be happy to fix it as much as possible by the user.)
I'll be in touch if you have any requests for additional features, thanks!

**Comment by codeflorist** [comment]
@ni1chigo2115 ah, sorry.  i didn't realize those links only work for me. here is a public link for RC2:
https://mega.nz/file/EbE33Iwa#c-XluGed-8Jlay5Sq8getepzlu-Fr9G_NSTSe3v4Qbw

**Comment by ni1chigo2115** [comment]
i tested 
Weapon position preset switching is working well, great!
(Maybe when QuakeSpasm officially supports the md5 format like Spiked Fork, they should add another position preset)
https://github.com/gameflorist/quakespasm-openvr/assets/23652237/225d2e5b-4e2b-4d84-8d3a-a6ca1a56c08e

**Comment by ni1chigo2115** [comment]
Now we can CLOSED this ISSUE once this BUILD is officially released.
